// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.hero;

public final class HeroAttribute {
  private HeroAttribute() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hero.Hero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>required int64 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int64 level = 3;</code>
     */
    long getLevel();

    /**
     * <code>required int64 fight = 4;</code>
     */
    boolean hasFight();
    /**
     * <code>required int64 fight = 4;</code>
     */
    long getFight();

    /**
     * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
     */
    boolean hasRoleType();
    /**
     * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
     */
    com.hero.HeroAttribute.Hero.RoleType getRoleType();

    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    boolean hasUniqueSystem();
    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    com.hero.HeroAttribute.Hero.UniqueSystem getUniqueSystem();
    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder getUniqueSystemOrBuilder();
  }
  /**
   * Protobuf type {@code com.hero.Hero}
   */
  public  static final class Hero extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.hero.Hero)
      HeroOrBuilder {
    // Use Hero.newBuilder() to construct.
    private Hero(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Hero() {
      name_ = "";
      id_ = 0;
      level_ = 0L;
      fight_ = 0L;
      roleType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              fight_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.hero.HeroAttribute.Hero.RoleType value = com.hero.HeroAttribute.Hero.RoleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                roleType_ = rawValue;
              }
              break;
            }
            case 50: {
              com.hero.HeroAttribute.Hero.UniqueSystem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = uniqueSystem_.toBuilder();
              }
              uniqueSystem_ = input.readMessage(com.hero.HeroAttribute.Hero.UniqueSystem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(uniqueSystem_);
                uniqueSystem_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hero.HeroAttribute.internal_static_com_hero_Hero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hero.HeroAttribute.internal_static_com_hero_Hero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hero.HeroAttribute.Hero.class, com.hero.HeroAttribute.Hero.Builder.class);
    }

    /**
     * Protobuf enum {@code com.hero.Hero.RoleType}
     */
    public enum RoleType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WARRIOR = 0;</code>
       */
      WARRIOR(0, 0),
      /**
       * <code>MAGER = 1;</code>
       */
      MAGER(1, 1),
      /**
       * <code>PASTOR = 2;</code>
       */
      PASTOR(2, 2),
      ;

      /**
       * <code>WARRIOR = 0;</code>
       */
      public static final int WARRIOR_VALUE = 0;
      /**
       * <code>MAGER = 1;</code>
       */
      public static final int MAGER_VALUE = 1;
      /**
       * <code>PASTOR = 2;</code>
       */
      public static final int PASTOR_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static RoleType valueOf(int value) {
        switch (value) {
          case 0: return WARRIOR;
          case 1: return MAGER;
          case 2: return PASTOR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RoleType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
              public RoleType findValueByNumber(int number) {
                return RoleType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hero.HeroAttribute.Hero.getDescriptor().getEnumTypes().get(0);
      }

      private static final RoleType[] VALUES = values();

      public static RoleType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RoleType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.hero.Hero.RoleType)
    }

    public interface UniqueSystemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.hero.Hero.UniqueSystem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 hores = 1;</code>
       */
      boolean hasHores();
      /**
       * <code>required int32 hores = 1;</code>
       */
      int getHores();

      /**
       * <code>required int32 wings = 2;</code>
       */
      boolean hasWings();
      /**
       * <code>required int32 wings = 2;</code>
       */
      int getWings();
    }
    /**
     * Protobuf type {@code com.hero.Hero.UniqueSystem}
     */
    public  static final class UniqueSystem extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.hero.Hero.UniqueSystem)
        UniqueSystemOrBuilder {
      // Use UniqueSystem.newBuilder() to construct.
      private UniqueSystem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private UniqueSystem() {
        hores_ = 0;
        wings_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private UniqueSystem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                hores_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                wings_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hero.HeroAttribute.internal_static_com_hero_Hero_UniqueSystem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hero.HeroAttribute.internal_static_com_hero_Hero_UniqueSystem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hero.HeroAttribute.Hero.UniqueSystem.class, com.hero.HeroAttribute.Hero.UniqueSystem.Builder.class);
      }

      private int bitField0_;
      public static final int HORES_FIELD_NUMBER = 1;
      private int hores_;
      /**
       * <code>required int32 hores = 1;</code>
       */
      public boolean hasHores() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 hores = 1;</code>
       */
      public int getHores() {
        return hores_;
      }

      public static final int WINGS_FIELD_NUMBER = 2;
      private int wings_;
      /**
       * <code>required int32 wings = 2;</code>
       */
      public boolean hasWings() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 wings = 2;</code>
       */
      public int getWings() {
        return wings_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasHores()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWings()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, hores_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, wings_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, hores_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, wings_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hero.HeroAttribute.Hero.UniqueSystem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.hero.HeroAttribute.Hero.UniqueSystem prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.hero.Hero.UniqueSystem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.hero.Hero.UniqueSystem)
          com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hero.HeroAttribute.internal_static_com_hero_Hero_UniqueSystem_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hero.HeroAttribute.internal_static_com_hero_Hero_UniqueSystem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.hero.HeroAttribute.Hero.UniqueSystem.class, com.hero.HeroAttribute.Hero.UniqueSystem.Builder.class);
        }

        // Construct using com.hero.HeroAttribute.Hero.UniqueSystem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          hores_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          wings_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hero.HeroAttribute.internal_static_com_hero_Hero_UniqueSystem_descriptor;
        }

        public com.hero.HeroAttribute.Hero.UniqueSystem getDefaultInstanceForType() {
          return com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance();
        }

        public com.hero.HeroAttribute.Hero.UniqueSystem build() {
          com.hero.HeroAttribute.Hero.UniqueSystem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.hero.HeroAttribute.Hero.UniqueSystem buildPartial() {
          com.hero.HeroAttribute.Hero.UniqueSystem result = new com.hero.HeroAttribute.Hero.UniqueSystem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.hores_ = hores_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.wings_ = wings_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hero.HeroAttribute.Hero.UniqueSystem) {
            return mergeFrom((com.hero.HeroAttribute.Hero.UniqueSystem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.hero.HeroAttribute.Hero.UniqueSystem other) {
          if (other == com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance()) return this;
          if (other.hasHores()) {
            setHores(other.getHores());
          }
          if (other.hasWings()) {
            setWings(other.getWings());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHores()) {
            return false;
          }
          if (!hasWings()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.hero.HeroAttribute.Hero.UniqueSystem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.hero.HeroAttribute.Hero.UniqueSystem) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int hores_ ;
        /**
         * <code>required int32 hores = 1;</code>
         */
        public boolean hasHores() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 hores = 1;</code>
         */
        public int getHores() {
          return hores_;
        }
        /**
         * <code>required int32 hores = 1;</code>
         */
        public Builder setHores(int value) {
          bitField0_ |= 0x00000001;
          hores_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 hores = 1;</code>
         */
        public Builder clearHores() {
          bitField0_ = (bitField0_ & ~0x00000001);
          hores_ = 0;
          onChanged();
          return this;
        }

        private int wings_ ;
        /**
         * <code>required int32 wings = 2;</code>
         */
        public boolean hasWings() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 wings = 2;</code>
         */
        public int getWings() {
          return wings_;
        }
        /**
         * <code>required int32 wings = 2;</code>
         */
        public Builder setWings(int value) {
          bitField0_ |= 0x00000002;
          wings_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 wings = 2;</code>
         */
        public Builder clearWings() {
          bitField0_ = (bitField0_ & ~0x00000002);
          wings_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.hero.Hero.UniqueSystem)
      }

      // @@protoc_insertion_point(class_scope:com.hero.Hero.UniqueSystem)
      private static final com.hero.HeroAttribute.Hero.UniqueSystem DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.hero.HeroAttribute.Hero.UniqueSystem();
      }

      public static com.hero.HeroAttribute.Hero.UniqueSystem getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<UniqueSystem>
          PARSER = new com.google.protobuf.AbstractParser<UniqueSystem>() {
        public UniqueSystem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new UniqueSystem(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<UniqueSystem> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UniqueSystem> getParserForType() {
        return PARSER;
      }

      public com.hero.HeroAttribute.Hero.UniqueSystem getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private long level_;
    /**
     * <code>required int64 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 level = 3;</code>
     */
    public long getLevel() {
      return level_;
    }

    public static final int FIGHT_FIELD_NUMBER = 4;
    private long fight_;
    /**
     * <code>required int64 fight = 4;</code>
     */
    public boolean hasFight() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 fight = 4;</code>
     */
    public long getFight() {
      return fight_;
    }

    public static final int ROLE_TYPE_FIELD_NUMBER = 5;
    private int roleType_;
    /**
     * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
     */
    public boolean hasRoleType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
     */
    public com.hero.HeroAttribute.Hero.RoleType getRoleType() {
      com.hero.HeroAttribute.Hero.RoleType result = com.hero.HeroAttribute.Hero.RoleType.valueOf(roleType_);
      return result == null ? com.hero.HeroAttribute.Hero.RoleType.WARRIOR : result;
    }

    public static final int UNIQUE_SYSTEM_FIELD_NUMBER = 6;
    private com.hero.HeroAttribute.Hero.UniqueSystem uniqueSystem_;
    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    public boolean hasUniqueSystem() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    public com.hero.HeroAttribute.Hero.UniqueSystem getUniqueSystem() {
      return uniqueSystem_ == null ? com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance() : uniqueSystem_;
    }
    /**
     * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
     */
    public com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder getUniqueSystemOrBuilder() {
      return uniqueSystem_ == null ? com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance() : uniqueSystem_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUniqueSystem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUniqueSystem().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, fight_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, roleType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, getUniqueSystem());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fight_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, roleType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getUniqueSystem());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.hero.HeroAttribute.Hero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hero.HeroAttribute.Hero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hero.HeroAttribute.Hero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hero.HeroAttribute.Hero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hero.HeroAttribute.Hero prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hero.Hero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hero.Hero)
        com.hero.HeroAttribute.HeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hero.HeroAttribute.internal_static_com_hero_Hero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hero.HeroAttribute.internal_static_com_hero_Hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hero.HeroAttribute.Hero.class, com.hero.HeroAttribute.Hero.Builder.class);
      }

      // Construct using com.hero.HeroAttribute.Hero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUniqueSystemFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        fight_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        roleType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (uniqueSystemBuilder_ == null) {
          uniqueSystem_ = null;
        } else {
          uniqueSystemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hero.HeroAttribute.internal_static_com_hero_Hero_descriptor;
      }

      public com.hero.HeroAttribute.Hero getDefaultInstanceForType() {
        return com.hero.HeroAttribute.Hero.getDefaultInstance();
      }

      public com.hero.HeroAttribute.Hero build() {
        com.hero.HeroAttribute.Hero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hero.HeroAttribute.Hero buildPartial() {
        com.hero.HeroAttribute.Hero result = new com.hero.HeroAttribute.Hero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fight_ = fight_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.roleType_ = roleType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (uniqueSystemBuilder_ == null) {
          result.uniqueSystem_ = uniqueSystem_;
        } else {
          result.uniqueSystem_ = uniqueSystemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hero.HeroAttribute.Hero) {
          return mergeFrom((com.hero.HeroAttribute.Hero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hero.HeroAttribute.Hero other) {
        if (other == com.hero.HeroAttribute.Hero.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasFight()) {
          setFight(other.getFight());
        }
        if (other.hasRoleType()) {
          setRoleType(other.getRoleType());
        }
        if (other.hasUniqueSystem()) {
          mergeUniqueSystem(other.getUniqueSystem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasLevel()) {
          return false;
        }
        if (!hasFight()) {
          return false;
        }
        if (!hasRoleType()) {
          return false;
        }
        if (!hasUniqueSystem()) {
          return false;
        }
        if (!getUniqueSystem().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hero.HeroAttribute.Hero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hero.HeroAttribute.Hero) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private long level_ ;
      /**
       * <code>required int64 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 level = 3;</code>
       */
      public long getLevel() {
        return level_;
      }
      /**
       * <code>required int64 level = 3;</code>
       */
      public Builder setLevel(long value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0L;
        onChanged();
        return this;
      }

      private long fight_ ;
      /**
       * <code>required int64 fight = 4;</code>
       */
      public boolean hasFight() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 fight = 4;</code>
       */
      public long getFight() {
        return fight_;
      }
      /**
       * <code>required int64 fight = 4;</code>
       */
      public Builder setFight(long value) {
        bitField0_ |= 0x00000008;
        fight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fight = 4;</code>
       */
      public Builder clearFight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fight_ = 0L;
        onChanged();
        return this;
      }

      private int roleType_ = 0;
      /**
       * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
       */
      public boolean hasRoleType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
       */
      public com.hero.HeroAttribute.Hero.RoleType getRoleType() {
        com.hero.HeroAttribute.Hero.RoleType result = com.hero.HeroAttribute.Hero.RoleType.valueOf(roleType_);
        return result == null ? com.hero.HeroAttribute.Hero.RoleType.WARRIOR : result;
      }
      /**
       * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
       */
      public Builder setRoleType(com.hero.HeroAttribute.Hero.RoleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        roleType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hero.Hero.RoleType role_type = 5;</code>
       */
      public Builder clearRoleType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roleType_ = 0;
        onChanged();
        return this;
      }

      private com.hero.HeroAttribute.Hero.UniqueSystem uniqueSystem_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.hero.HeroAttribute.Hero.UniqueSystem, com.hero.HeroAttribute.Hero.UniqueSystem.Builder, com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder> uniqueSystemBuilder_;
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public boolean hasUniqueSystem() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public com.hero.HeroAttribute.Hero.UniqueSystem getUniqueSystem() {
        if (uniqueSystemBuilder_ == null) {
          return uniqueSystem_ == null ? com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance() : uniqueSystem_;
        } else {
          return uniqueSystemBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public Builder setUniqueSystem(com.hero.HeroAttribute.Hero.UniqueSystem value) {
        if (uniqueSystemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uniqueSystem_ = value;
          onChanged();
        } else {
          uniqueSystemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public Builder setUniqueSystem(
          com.hero.HeroAttribute.Hero.UniqueSystem.Builder builderForValue) {
        if (uniqueSystemBuilder_ == null) {
          uniqueSystem_ = builderForValue.build();
          onChanged();
        } else {
          uniqueSystemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public Builder mergeUniqueSystem(com.hero.HeroAttribute.Hero.UniqueSystem value) {
        if (uniqueSystemBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              uniqueSystem_ != null &&
              uniqueSystem_ != com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance()) {
            uniqueSystem_ =
              com.hero.HeroAttribute.Hero.UniqueSystem.newBuilder(uniqueSystem_).mergeFrom(value).buildPartial();
          } else {
            uniqueSystem_ = value;
          }
          onChanged();
        } else {
          uniqueSystemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public Builder clearUniqueSystem() {
        if (uniqueSystemBuilder_ == null) {
          uniqueSystem_ = null;
          onChanged();
        } else {
          uniqueSystemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public com.hero.HeroAttribute.Hero.UniqueSystem.Builder getUniqueSystemBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getUniqueSystemFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      public com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder getUniqueSystemOrBuilder() {
        if (uniqueSystemBuilder_ != null) {
          return uniqueSystemBuilder_.getMessageOrBuilder();
        } else {
          return uniqueSystem_ == null ?
              com.hero.HeroAttribute.Hero.UniqueSystem.getDefaultInstance() : uniqueSystem_;
        }
      }
      /**
       * <code>required .com.hero.Hero.UniqueSystem unique_system = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hero.HeroAttribute.Hero.UniqueSystem, com.hero.HeroAttribute.Hero.UniqueSystem.Builder, com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder> 
          getUniqueSystemFieldBuilder() {
        if (uniqueSystemBuilder_ == null) {
          uniqueSystemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hero.HeroAttribute.Hero.UniqueSystem, com.hero.HeroAttribute.Hero.UniqueSystem.Builder, com.hero.HeroAttribute.Hero.UniqueSystemOrBuilder>(
                  getUniqueSystem(),
                  getParentForChildren(),
                  isClean());
          uniqueSystem_ = null;
        }
        return uniqueSystemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.hero.Hero)
    }

    // @@protoc_insertion_point(class_scope:com.hero.Hero)
    private static final com.hero.HeroAttribute.Hero DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hero.HeroAttribute.Hero();
    }

    public static com.hero.HeroAttribute.Hero getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Hero>
        PARSER = new com.google.protobuf.AbstractParser<Hero>() {
      public Hero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Hero(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Hero> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hero> getParserForType() {
      return PARSER;
    }

    public com.hero.HeroAttribute.Hero getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeroListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hero.HeroList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    java.util.List<com.hero.HeroAttribute.Hero> 
        getHeroList();
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    com.hero.HeroAttribute.Hero getHero(int index);
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    int getHeroCount();
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    java.util.List<? extends com.hero.HeroAttribute.HeroOrBuilder> 
        getHeroOrBuilderList();
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    com.hero.HeroAttribute.HeroOrBuilder getHeroOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.hero.HeroList}
   */
  public  static final class HeroList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.hero.HeroList)
      HeroListOrBuilder {
    // Use HeroList.newBuilder() to construct.
    private HeroList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HeroList() {
      hero_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeroList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                hero_ = new java.util.ArrayList<com.hero.HeroAttribute.Hero>();
                mutable_bitField0_ |= 0x00000001;
              }
              hero_.add(input.readMessage(com.hero.HeroAttribute.Hero.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          hero_ = java.util.Collections.unmodifiableList(hero_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hero.HeroAttribute.internal_static_com_hero_HeroList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hero.HeroAttribute.internal_static_com_hero_HeroList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hero.HeroAttribute.HeroList.class, com.hero.HeroAttribute.HeroList.Builder.class);
    }

    public static final int HERO_FIELD_NUMBER = 1;
    private java.util.List<com.hero.HeroAttribute.Hero> hero_;
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    public java.util.List<com.hero.HeroAttribute.Hero> getHeroList() {
      return hero_;
    }
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    public java.util.List<? extends com.hero.HeroAttribute.HeroOrBuilder> 
        getHeroOrBuilderList() {
      return hero_;
    }
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    public int getHeroCount() {
      return hero_.size();
    }
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    public com.hero.HeroAttribute.Hero getHero(int index) {
      return hero_.get(index);
    }
    /**
     * <code>repeated .com.hero.Hero hero = 1;</code>
     */
    public com.hero.HeroAttribute.HeroOrBuilder getHeroOrBuilder(
        int index) {
      return hero_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHeroCount(); i++) {
        if (!getHero(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hero_.size(); i++) {
        output.writeMessage(1, hero_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hero_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hero_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.hero.HeroAttribute.HeroList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hero.HeroAttribute.HeroList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hero.HeroAttribute.HeroList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hero.HeroAttribute.HeroList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hero.HeroAttribute.HeroList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hero.HeroList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hero.HeroList)
        com.hero.HeroAttribute.HeroListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hero.HeroAttribute.internal_static_com_hero_HeroList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hero.HeroAttribute.internal_static_com_hero_HeroList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hero.HeroAttribute.HeroList.class, com.hero.HeroAttribute.HeroList.Builder.class);
      }

      // Construct using com.hero.HeroAttribute.HeroList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeroFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          heroBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hero.HeroAttribute.internal_static_com_hero_HeroList_descriptor;
      }

      public com.hero.HeroAttribute.HeroList getDefaultInstanceForType() {
        return com.hero.HeroAttribute.HeroList.getDefaultInstance();
      }

      public com.hero.HeroAttribute.HeroList build() {
        com.hero.HeroAttribute.HeroList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hero.HeroAttribute.HeroList buildPartial() {
        com.hero.HeroAttribute.HeroList result = new com.hero.HeroAttribute.HeroList(this);
        int from_bitField0_ = bitField0_;
        if (heroBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            hero_ = java.util.Collections.unmodifiableList(hero_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hero_ = hero_;
        } else {
          result.hero_ = heroBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hero.HeroAttribute.HeroList) {
          return mergeFrom((com.hero.HeroAttribute.HeroList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hero.HeroAttribute.HeroList other) {
        if (other == com.hero.HeroAttribute.HeroList.getDefaultInstance()) return this;
        if (heroBuilder_ == null) {
          if (!other.hero_.isEmpty()) {
            if (hero_.isEmpty()) {
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeroIsMutable();
              hero_.addAll(other.hero_);
            }
            onChanged();
          }
        } else {
          if (!other.hero_.isEmpty()) {
            if (heroBuilder_.isEmpty()) {
              heroBuilder_.dispose();
              heroBuilder_ = null;
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000001);
              heroBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHeroFieldBuilder() : null;
            } else {
              heroBuilder_.addAllMessages(other.hero_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getHeroCount(); i++) {
          if (!getHero(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hero.HeroAttribute.HeroList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hero.HeroAttribute.HeroList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.hero.HeroAttribute.Hero> hero_ =
        java.util.Collections.emptyList();
      private void ensureHeroIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          hero_ = new java.util.ArrayList<com.hero.HeroAttribute.Hero>(hero_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hero.HeroAttribute.Hero, com.hero.HeroAttribute.Hero.Builder, com.hero.HeroAttribute.HeroOrBuilder> heroBuilder_;

      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public java.util.List<com.hero.HeroAttribute.Hero> getHeroList() {
        if (heroBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hero_);
        } else {
          return heroBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public int getHeroCount() {
        if (heroBuilder_ == null) {
          return hero_.size();
        } else {
          return heroBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public com.hero.HeroAttribute.Hero getHero(int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);
        } else {
          return heroBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder setHero(
          int index, com.hero.HeroAttribute.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.set(index, value);
          onChanged();
        } else {
          heroBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder setHero(
          int index, com.hero.HeroAttribute.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.set(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder addHero(com.hero.HeroAttribute.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(value);
          onChanged();
        } else {
          heroBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder addHero(
          int index, com.hero.HeroAttribute.Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(index, value);
          onChanged();
        } else {
          heroBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder addHero(
          com.hero.HeroAttribute.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder addHero(
          int index, com.hero.HeroAttribute.Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder addAllHero(
          java.lang.Iterable<? extends com.hero.HeroAttribute.Hero> values) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hero_);
          onChanged();
        } else {
          heroBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder clearHero() {
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          heroBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public Builder removeHero(int index) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.remove(index);
          onChanged();
        } else {
          heroBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public com.hero.HeroAttribute.Hero.Builder getHeroBuilder(
          int index) {
        return getHeroFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public com.hero.HeroAttribute.HeroOrBuilder getHeroOrBuilder(
          int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);  } else {
          return heroBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public java.util.List<? extends com.hero.HeroAttribute.HeroOrBuilder> 
           getHeroOrBuilderList() {
        if (heroBuilder_ != null) {
          return heroBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hero_);
        }
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public com.hero.HeroAttribute.Hero.Builder addHeroBuilder() {
        return getHeroFieldBuilder().addBuilder(
            com.hero.HeroAttribute.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public com.hero.HeroAttribute.Hero.Builder addHeroBuilder(
          int index) {
        return getHeroFieldBuilder().addBuilder(
            index, com.hero.HeroAttribute.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hero.Hero hero = 1;</code>
       */
      public java.util.List<com.hero.HeroAttribute.Hero.Builder> 
           getHeroBuilderList() {
        return getHeroFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hero.HeroAttribute.Hero, com.hero.HeroAttribute.Hero.Builder, com.hero.HeroAttribute.HeroOrBuilder> 
          getHeroFieldBuilder() {
        if (heroBuilder_ == null) {
          heroBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hero.HeroAttribute.Hero, com.hero.HeroAttribute.Hero.Builder, com.hero.HeroAttribute.HeroOrBuilder>(
                  hero_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          hero_ = null;
        }
        return heroBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.hero.HeroList)
    }

    // @@protoc_insertion_point(class_scope:com.hero.HeroList)
    private static final com.hero.HeroAttribute.HeroList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hero.HeroAttribute.HeroList();
    }

    public static com.hero.HeroAttribute.HeroList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeroList>
        PARSER = new com.google.protobuf.AbstractParser<HeroList>() {
      public HeroList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new HeroList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<HeroList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeroList> getParserForType() {
      return PARSER;
    }

    public com.hero.HeroAttribute.HeroList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hero_Hero_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hero_Hero_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hero_Hero_UniqueSystem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hero_Hero_UniqueSystem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hero_HeroList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hero_HeroList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010com.hero\"\374\001\n\004Hero\022\014\n\004name\030" +
      "\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005level\030\003 \002(\003\022\r\n\005figh" +
      "t\030\004 \002(\003\022*\n\trole_type\030\005 \002(\0162\027.com.hero.He" +
      "ro.RoleType\0222\n\runique_system\030\006 \002(\0132\033.com" +
      ".hero.Hero.UniqueSystem\032,\n\014UniqueSystem\022" +
      "\r\n\005hores\030\001 \002(\005\022\r\n\005wings\030\002 \002(\005\".\n\010RoleTyp" +
      "e\022\013\n\007WARRIOR\020\000\022\t\n\005MAGER\020\001\022\n\n\006PASTOR\020\002\"(\n" +
      "\010HeroList\022\034\n\004hero\030\001 \003(\0132\016.com.hero.HeroB" +
      "\031\n\010com.heroB\rHeroAttribute"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hero_Hero_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hero_Hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hero_Hero_descriptor,
        new java.lang.String[] { "Name", "Id", "Level", "Fight", "RoleType", "UniqueSystem", });
    internal_static_com_hero_Hero_UniqueSystem_descriptor =
      internal_static_com_hero_Hero_descriptor.getNestedTypes().get(0);
    internal_static_com_hero_Hero_UniqueSystem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hero_Hero_UniqueSystem_descriptor,
        new java.lang.String[] { "Hores", "Wings", });
    internal_static_com_hero_HeroList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hero_HeroList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hero_HeroList_descriptor,
        new java.lang.String[] { "Hero", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
